spring:
    application:
        name: distances
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config
            request-connected-timeout: 5000
            request-read-timeout: 5000
            fail-fast: true
            retry:
                max-attempts: 6
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1
    config:
        import: "optional:configserver:"

server:
    port: ${SERVER_PORT:8181}

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
    tracing:
        enabled: true
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
