spring:
    application:
        name: distances
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config
    config:
        import: "optional:configserver:"

server:
    port: ${SERVER_PORT:8181}

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
